### ISSUE TITLE
Names do not match.

### ISSUE THREAD

**Issue by dmitshur** [dinedal/message_droid#1]
The name of repository and the name in README are not the same.

**Comment by dmitshur** [comment]
Any thoughts about which way to resolve this?

**Comment by dmitshur** [comment]
I have very little preference which way this is resolved, but I would like to resolve the issue.

To pick a random one, let's go with `message_droid` as the name. Any objections?

**Comment by dmitshur** [comment]
Friendly ping. We're so close to wrapping this up, and lowering mental overhead.

**Comment by dinedal** [comment]
Closed by 2ffa12d02827389f4ed53c1f51d4831fc7ccbe8b

**Comment by dmitshur** [comment]
Why not via #3? 2ffa12d seems to miss a few files (README and services/float_time/main.go) and breaks `gofmt`ing.
